name: Windows

on: [push, pull_request]

jobs:
  build:
    runs-on: windows-2019

    strategy:
      matrix:
        toolset: [MSVC]
        configuration: [Debug, Release]

    steps:
    - uses: actions/checkout@v2
    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.1
      
    - name: Build
      shell: cmd
      run: msbuild Osiris.sln /p:Platform=x86 /p:Configuration=${{ matrix.configuration }} ${{ env.toolset }}
